# Generated by Django 3.0.7 on 2020-09-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
