# Generated by Django 3.0.7 on 2020-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliveryaddress',
            constraint=models.UniqueConstraint(fields=('user', 'address_ref'), name='unique address'),
        ),
    ]
