# Generated by Django 3.0.7 on 2020-09-15 14:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200915_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
