# Generated by Django 3.0.7 on 2020-09-03 18:13

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('img', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('relevant_model', models.CharField(default='Supplies', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skus', jsonfield.fields.JSONField(null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('img', models.CharField(blank=True, max_length=254, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(null=True)),
                ('blurb', models.TextField(null=True)),
                ('related_printers', jsonfield.fields.JSONField(null=True)),
                ('features', jsonfield.fields.JSONField(null=True)),
                ('keywords', jsonfield.fields.JSONField(null=True)),
                ('published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
        ),
    ]
