# Generated by Django 3.0.7 on 2020-09-25 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('img', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('relevant_model', models.CharField(default='supplies', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profit_margin', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='VatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vat_rate', models.IntegerField(default=21, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skus', jsonfield.fields.JSONField(null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('img_src', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(null=True)),
                ('blurb', models.TextField(null=True)),
                ('features', jsonfield.fields.JSONField(null=True)),
                ('published', models.BooleanField(default=True)),
                ('related_printers', jsonfield.fields.JSONField(null=True)),
                ('brochure', models.CharField(blank=True, max_length=254, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
                ('product_group', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductGroup')),
                ('vat_rate', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.VatGroup')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
