# Generated by Django 3.0.7 on 2020-09-25 08:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='related_printers',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
