# Generated by Django 3.0.7 on 2020-09-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productgroup_vatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='supplies',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='supplies',
            name='product_group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductGroup'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='vat_rate',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.VatGroup'),
        ),
    ]
