# Generated by Django 3.0.7 on 2020-09-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200906_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
